swagger: "2.0"
info:
  title: Tekton Hub
  description: HTTP services for managing Tekton Hub
  version: "1.0"
host: localhost:8000
consumes:
- application/json
- application/xml
- application/gob
produces:
- application/json
- application/xml
- application/gob
paths:
  /categories:
    get:
      tags:
      - category
      summary: All category
      description: Get all Categories with their tags sorted by name
      operationId: category#All
      responses:
        "200":
          description: OK response.
          schema:
            type: array
            items:
              $ref: '#/definitions/categoryResponse'
        "500":
          description: Internal Server Error response.
          schema:
            $ref: '#/definitions/CategoryAllInternalErrorResponseBody'
      schemes:
      - http
  /resources:
    get:
      tags:
      - resource
      summary: AllResources resource
      description: Get all Resources
      operationId: resource#AllResources
      parameters:
      - name: limit
        in: query
        description: Number of resources
        required: false
        type: integer
        default: 100
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/ResourceResourceResponseExtendedCollection'
        "500":
          description: Internal Server Error response.
          schema:
            $ref: '#/definitions/ResourceAllResourcesDbDownResponseBody'
      schemes:
      - http
  /swagger/swagger.json:
    get:
      tags:
      - swagger
      summary: Download gen/http/openapi.json
      description: JSON document containing the API swagger definition
      operationId: swagger#/swagger/swagger.json
      responses:
        "200":
          description: File downloaded
          schema:
            type: file
      schemes:
      - http
definitions:
  CatalogResponse:
    title: CatalogResponse
    type: object
    properties:
      id:
        type: integer
        description: ID is the unique id of the catalog
        example: 1
        format: int64
      type:
        type: string
        description: Type of catalog
        example: Official
    example:
      id: 1
      type: Official
    required:
    - id
    - type
  CategoryAllInternalErrorResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: true
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: true
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: false
    description: All_internal-error_Response_Body result type (default view)
    example:
      fault: true
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: true
      timeout: true
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  ResourceAllResourcesDbDownResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: false
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: false
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: true
    description: AllResources_db-down_Response_Body result type (default view)
    example:
      fault: true
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: false
      timeout: true
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  ResourceResourceResponseExtendedCollection:
    title: 'Mediatype identifier: application/vnd.hub.resource; type=collection; view=extended'
    type: array
    items:
      $ref: '#/definitions/ResourceResponseExtended'
    description: ResourceResourceResponseExtendedCollection is the result type for
      an array of ResourceResponseExtended (default view)
    example:
    - catalog:
        id: 1
        type: Official
      description: This Task is Golang task to build Go projects
      displayName: golang
      id: 1
      last_updated_at: "2020-03-26T14:09:08.19599+05:30"
      latest_version: "0.1"
      name: golang
      rating: 5
      tags:
      - id: 1
        name: cli
      - id: 1
        name: cli
      - id: 1
        name: cli
      - id: 1
        name: cli
      type: task
    - catalog:
        id: 1
        type: Official
      description: This Task is Golang task to build Go projects
      displayName: golang
      id: 1
      last_updated_at: "2020-03-26T14:09:08.19599+05:30"
      latest_version: "0.1"
      name: golang
      rating: 5
      tags:
      - id: 1
        name: cli
      - id: 1
        name: cli
      - id: 1
        name: cli
      - id: 1
        name: cli
      type: task
    - catalog:
        id: 1
        type: Official
      description: This Task is Golang task to build Go projects
      displayName: golang
      id: 1
      last_updated_at: "2020-03-26T14:09:08.19599+05:30"
      latest_version: "0.1"
      name: golang
      rating: 5
      tags:
      - id: 1
        name: cli
      - id: 1
        name: cli
      - id: 1
        name: cli
      - id: 1
        name: cli
      type: task
  ResourceResponseExtended:
    title: 'Mediatype identifier: application/vnd.hub.resource; view=default'
    type: object
    properties:
      catalog:
        $ref: '#/definitions/CatalogResponse'
      description:
        type: string
        description: Description of resource
        example: This Task is Golang task to build Go projects
      displayName:
        type: string
        description: Display name of the resource
        example: golang
      id:
        type: integer
        description: ID is the unique id of the resource
        example: 1
        format: int64
      last_updated_at:
        type: string
        description: Date when resource was last updated
        example: "2020-03-26T14:09:08.19599+05:30"
      latest_version:
        type: string
        description: Latest version o resource
        example: "0.1"
      name:
        type: string
        description: Name of the resource
        example: golang
      rating:
        type: integer
        description: Rating of resource
        example: 5
        format: int64
      tags:
        type: array
        items:
          $ref: '#/definitions/TagResponse'
        description: Tags related to resources
        example:
        - id: 1
          name: cli
        - id: 1
          name: cli
        - id: 1
          name: cli
      type:
        type: string
        description: Type of resource
        example: task
    description: The resource service provides all resources information. (extended
      view) (default view)
    example:
      catalog:
        id: 1
        type: Official
      description: This Task is Golang task to build Go projects
      displayName: golang
      id: 1
      last_updated_at: "2020-03-26T14:09:08.19599+05:30"
      latest_version: "0.1"
      name: golang
      rating: 5
      tags:
      - id: 1
        name: cli
      - id: 1
        name: cli
      - id: 1
        name: cli
      - id: 1
        name: cli
      type: task
    required:
    - id
    - name
    - displayName
    - catalog
    - type
    - description
    - latest_version
    - tags
    - rating
    - last_updated_at
  TagResponse:
    title: TagResponse
    type: object
    properties:
      id:
        type: integer
        description: Id is the unique id of tags
        example: 1
        format: int64
      name:
        type: string
        description: name of tag
        example: cli
    example:
      id: 1
      name: cli
    required:
    - id
    - name
  categoryResponse:
    title: categoryResponse
    type: object
    properties:
      id:
        type: integer
        description: unique id of category
        example: 1
        format: int64
      name:
        type: string
        description: name of category
        example: Image-build
      tags:
        type: array
        items:
          $ref: '#/definitions/TagResponse'
        description: list of tag associated with category
        example:
        - id: 1
          name: cli
        - id: 1
          name: cli
    example:
      id: 1
      name: Image-build
      tags:
      - id: 1
        name: cli
      - id: 1
        name: cli
      - id: 1
        name: cli
    required:
    - id
    - name
    - tags
